[tool.poetry]
name = "icelinbot"
version = "0.1.0"
description = ""
authors = ["Icelin <icelin_channel@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
